### ISSUE TITLE
쓰레드에 이모티콘 달기 실패

### ISSUE THREAD

**Issue by loin3** [boostcampwm-2021/web06-booslack#183]
# 📃 버그 설명

자세하게 설명하기

# 📃 버그 발생 부분 설명

Ex) 

# 📃 버그 발생 부분 화면

# 📃 추가 메모 사항

**Comment by laz** [comment]
영상 첨부합니다

콘솔에는 onEmojiSet 함수에서 현재 값을 찍게한 상황입니다.

https://user-images.githubusercontent.com/75822859/143998585-730133c5-5b20-4943-8050-0dc084875331.mov

.
