### ISSUE TITLE
접속한 사용자의 아이디와 다른 아이디로 인식하고 대부분의 사용자가 채팅이 불가능합니다.

### ISSUE THREAD

**Issue by blogSoul** [boostcampwm-2021/web06-booslack#195]
# 📃 버그 설명

접속한 사용자의 아이디와 다른 아이디로 인식하고 대부분의 사용자가 채팅이 불가능합니다.

# 📃 버그 발생 부분 설명

1. 접속한 사용자의 아이디와 다른 아이디로 인식됩니다.
2. 대부분의 사용자가 채팅이 불가능합니다.

# 📃 버그 발생 부분 화면

![image](https://user-images.githubusercontent.com/42922298/144314761-affa9f9f-dc0c-4b2d-aeaa-31921168e6bb.png)

# 📃 추가 메모 사항

**Comment by lodado** [comment]
잘못된 merge로 밝혀져서 닫겠씁니다
