### ISSUE TITLE
로그인이 안되면 SPA 라우팅 처리 안되게 해주세요! 

### ISSUE THREAD

**Issue by lodado** [boostcampwm-2021/web06-booslack#68]
# 📃 버그 설명

로그인이 완성되면 /workspace, /browsechannel 등 

로그인이 안되었다면 다른 페이지로 frontend 라우팅 처리시 

/login으로 경로를 바꾸도록 라우팅 처리해주세요!  

# 📃 버그 발생 부분 설명

로그인 안해도
/workspace 접근가능

# 📃 버그 발생 부분 화면

# 📃 추가 메모 사항

**Comment by blogSoul** [comment]
task나 다른 스프레트 시트 보시면 아시겠지만 아직 구현하지 않은 task 기능입니다. 이번 주 주말 이내로 구현해서 코멘트 남기겠습니다.🙌
