### ISSUE TITLE
프론트에서 axios를 쓰면 비동기 처리, 예외처리를 해주세요

### ISSUE THREAD

**Issue by lodado** [boostcampwm-2021/web06-booslack#69]
멘토님께서 지적해준 사항인데

비동기 처리할때 예외처리를 해주세요!

예시 코드입니다

``` javascript
const User = () => {
  const [data, loading, error, fetchRequest] = useAsync(
    null,
    'https://jsonplaceholder.typicode.com/users',
    [],
  );

  if (loading) return <div>로딩중..</div>;
  if (error) return <div>에러가 발생했습니다</div>;
  if (!data) return <div>11</div>;
  return (
    <>
      <div onClick={fetchRequest}>restart</div>
      <ul>
        {data.map((user) => (
          <li key={user.id}>
            {user.username}({user.name})
          </li>
        ))}
      </ul>
    </>
  );
}; 
```

1. loading - Axios를 쓰고 받아 오기 전에 보여줄 화면

2. 에러가 나오면 보여줄 화면

3. 데이터가 비었으면 보여줄 화면

3번 이후 return : 데이터를 받아와 출력할 화면 

아래 링크는 제가 쓰는 custom hook입니다 

https://github.com/lodado/web06-booslack/blob/dev/frontend/src/hooks/useAsync.ts

아래 링크는 제가 쓴 실제 코드 예시입니다

https://github.com/lodado/web06-booslack/blob/dev/frontend/src/components/organisms/BrowseChannelList/index.tsx

44번째줄 <AsyncBranch .../> 참고

**Comment by blogSoul** [comment]
```typescript
type METHOD = 'GET' | 'POST' | 'DELETE' | 'UPDATE';

const getAxios = async (Path: string, JSON: Data): Promise<Data> => {
  return axios.get(Path, JSON);
};

const postAxios = async (Path: string, JSON: Data): Promise<Data> => {
  return axios.post(Path, JSON);
};

const deleteAxios = (Path: string, JSON: Data): Promise<Data> => {
  return axios.delete(Path, JSON);
};

const updateAxios = async (Path: string, JSON: Data): Promise<Data> => {
  return axios.put(Path, JSON);
};

const getAxiosByMethod = (method: METHOD) => {
  if (method === 'POST') return postAxios;
  if (method === 'DELETE') return deleteAxios;
  if (method === 'UPDATE') return updateAxios;
  return getAxios;
};
```

커스텀 훅 두 개 만드셨는데, 아래에 있는 useAsync를 구현한 커스텀 훅은 한번 사용해볼 거 같습니다. 

근데, 위에 있는 axios를 간단하게 만든 커스텀 훅에서 옵션을 넣어줄 수 있는 부분도 추가되면 좀더 사용하기 용이할 것 같습니다!👍👍

잘 만드셨네요🙌🙌

**Comment by lodado** [comment]
원래 그런식으로 고차함수처럼 하려고 했는데 ts가 뭘 자꾸 뱉어내려고 하더라고요.. 그래서 string으로 인자를 받아 method를 지정해주는 식으로 했습니다 ㅠ

**Comment by lodado** [comment]
https://github.com/boostcampwm-2021/web06-booslack/blob/dev/frontend/src/hooks/usePagination.ts 는 axios를 받아서 사용하는 식으로 구현했습니다.

react-query 도 대부분 비동기 함수를 받아서 처리하는 방식이네요
