### ISSUE TITLE
자동완성 템플릿으로 추상화하기

### ISSUE THREAD

**Issue by laz** [boostcampwm-2021/web06-booslack#94]
# 📃 feature 설명

- onChange에 실행시킬 함수
- 완성된 목록 템플릿
을 입력받아서 자동완성 하도록 추상화

- debounce / throttle?

https://p-iknow.netlify.app/project/lib/auto-complete

# 📃 feature 구현 목록

# 📃 feature 구현시 고려할 사항

# 📃 추가 메모 사항

**Comment by lodado** [comment]
오.. 이거 되면 헤더에 넣으면 좋을꺼 같아요
